-- ============================================================
-- SkyBook — Airline Flight Booking & Revenue Management System
-- Query Set (used in the project report, Q1-Q30)
-- Database: SkyBookDB
-- ============================================================



-- Q1. List all flights departing from 'DEL'.
SELECT * FROM Flights WHERE Origin_Code = 'DEL';

-- Q2. Retrieve all bookings with status 'Cancelled'.
SELECT * FROM Bookings WHERE Status = 'Cancelled';

-- Q3. Display the 5 most expensive flights by base fare.
SELECT * FROM Flights ORDER BY Base_Fare DESC LIMIT 5;

-- Q4. Show the 3 most recently made bookings.
SELECT * FROM Bookings ORDER BY Booking_Date DESC LIMIT 3;

-- Q5. Find all flights booked by 'Aarav Mehta'.
SELECT f.Flight_Number, f.Origin_Code, f.Destination_Code, f.Departure_Date
FROM Bookings b
JOIN Flights f ON b.Flight_ID = f.Flight_ID
JOIN Passengers p ON b.Passenger_ID = p.Passenger_ID
WHERE p.Name = 'Aarav Mehta';

-- Q6. Display payments with an amount greater than the average payment amount.
SELECT * FROM Payments WHERE Amount > (SELECT AVG(Amount) FROM Payments);

-- Q7. Find the total number of bookings made by each passenger.
SELECT Passenger_ID, COUNT(*) AS Total_Bookings
FROM Bookings
GROUP BY Passenger_ID;

-- Q8. Find the average base fare for each airline.
SELECT Airline, ROUND(AVG(Base_Fare),2) AS Avg_Fare
FROM Flights
GROUP BY Airline;

-- Q9. Show the number of confirmed bookings.
SELECT COUNT(*) AS Confirmed_Bookings FROM Bookings WHERE Status = 'Confirmed';

-- Q10. Find the passenger who has spent the most on flights.
SELECT b.Passenger_ID, SUM(pay.Amount) AS Total_Spent
FROM Bookings b JOIN Payments pay ON b.Booking_ID = pay.Booking_ID
GROUP BY b.Passenger_ID ORDER BY Total_Spent DESC LIMIT 1;

-- Q11. Identify flights that have never been booked.
SELECT Flight_Number FROM Flights
WHERE Flight_ID NOT IN (SELECT DISTINCT Flight_ID FROM Bookings);

-- Q12. Calculate cumulative revenue by payment date (WINDOW FUNCTION: SUM() OVER).
SELECT Payment_Date, SUM(Amount) AS Daily_Revenue,
       SUM(SUM(Amount)) OVER (ORDER BY Payment_Date) AS Cumulative_Revenue
FROM Payments
GROUP BY Payment_Date
ORDER BY Payment_Date;

-- Q13. Find total revenue generated by each payment method.
SELECT Payment_Method, SUM(Amount) AS Total_Revenue
FROM Payments
GROUP BY Payment_Method;

-- Q14. Display the total amount paid by each passenger.
SELECT b.Passenger_ID, SUM(pay.Amount) AS Total_Paid
FROM Bookings b JOIN Payments pay ON b.Booking_ID = pay.Booking_ID
GROUP BY b.Passenger_ID;

-- Q15. Retrieve flights that received more than one booking.
SELECT Flight_ID, COUNT(*) AS Booking_Count
FROM Bookings
GROUP BY Flight_ID HAVING COUNT(*) > 1;

-- Q16. Show passengers who paid via 'UPI'.
SELECT DISTINCT p.Name FROM Passengers p
JOIN Bookings b ON p.Passenger_ID = b.Passenger_ID
JOIN Payments pay ON b.Booking_ID = pay.Booking_ID
WHERE pay.Payment_Method = 'UPI';

-- Q17. Retrieve the airline that generated the highest total revenue.
SELECT f.Airline, SUM(pay.Amount) AS Total_Revenue
FROM Flights f JOIN Bookings b ON f.Flight_ID = b.Flight_ID
JOIN Payments pay ON b.Booking_ID = pay.Booking_ID
GROUP BY f.Airline ORDER BY Total_Revenue DESC LIMIT 1;

-- Q18. Retrieve the top 3 passengers with the highest total spend.
SELECT b.Passenger_ID, SUM(pay.Amount) AS Total_Spent
FROM Bookings b JOIN Payments pay ON b.Booking_ID = pay.Booking_ID
GROUP BY b.Passenger_ID ORDER BY Total_Spent DESC LIMIT 3;

-- Q19. Find the payment method used for the most transactions.
SELECT Payment_Method, COUNT(*) AS Transaction_Count
FROM Payments
GROUP BY Payment_Method ORDER BY Transaction_Count DESC LIMIT 1;

-- Q20. List each airline with its highest fare flight.
SELECT Airline, MAX(Base_Fare) AS Max_Fare
FROM Flights
GROUP BY Airline;

-- Q21. Rank passengers by total spend (WINDOW FUNCTION: RANK()).
SELECT b.Passenger_ID, SUM(pay.Amount) AS Total_Spent,
       RANK() OVER (ORDER BY SUM(pay.Amount) DESC) AS Spend_Rank
FROM Bookings b JOIN Payments pay ON b.Booking_ID = pay.Booking_ID
GROUP BY b.Passenger_ID;

-- Q22. Number each passenger's bookings in chronological order (WINDOW FUNCTION: ROW_NUMBER() + PARTITION BY).
SELECT Passenger_ID, Booking_ID, Booking_Date,
       ROW_NUMBER() OVER (PARTITION BY Passenger_ID ORDER BY Booking_Date) AS Booking_Sequence
FROM Bookings;

-- Q23. Compare each flight's fare with the fare of the previous flight by departure date (WINDOW FUNCTION: LAG()).
SELECT Flight_ID, Departure_Date, Base_Fare,
       LAG(Base_Fare) OVER (ORDER BY Departure_Date) AS Previous_Flight_Fare
FROM Flights
ORDER BY Departure_Date;

-- Q24. Calculate a 3-day moving average of daily revenue (WINDOW FUNCTION: AVG() with a frame).
SELECT Payment_Date, SUM(Amount) AS Daily_Revenue,
       ROUND(AVG(SUM(Amount)) OVER (ORDER BY Payment_Date ROWS BETWEEN 2 PRECEDING AND CURRENT ROW),2) AS Moving_Avg_3Day
FROM Payments
GROUP BY Payment_Date
ORDER BY Payment_Date;

-- Q25. Split flights into 4 fare quartiles (WINDOW FUNCTION: NTILE()).
SELECT Flight_ID, Flight_Number, Base_Fare,
       NTILE(4) OVER (ORDER BY Base_Fare) AS Fare_Quartile
FROM Flights;

-- Q26. Use a CTE to find passengers whose total spend exceeds ₹9000.
WITH PassengerSpend AS (
    SELECT b.Passenger_ID, SUM(pay.Amount) AS Total_Spent
    FROM Bookings b JOIN Payments pay ON b.Booking_ID = pay.Booking_ID
    GROUP BY b.Passenger_ID
)
SELECT p.Name, ps.Total_Spent
FROM PassengerSpend ps JOIN Passengers p ON ps.Passenger_ID = p.Passenger_ID
WHERE ps.Total_Spent > 9000
ORDER BY ps.Total_Spent DESC;

-- Q27. Create an index to speed up searching bookings by passenger.
CREATE INDEX idx_passenger_id ON Bookings(Passenger_ID);

-- Q28. Create a unique index to prevent duplicate passenger emails.
CREATE UNIQUE INDEX idx_email ON Passengers(Email);

-- Q29. Create a view of high-value payments above ₹5000.
CREATE VIEW HighValuePayments AS
SELECT * FROM Payments WHERE Amount > 5000;

SELECT * FROM HighValuePayments;

-- Q30. Create a view for total revenue per airline.
CREATE VIEW AirlineRevenue AS
SELECT f.Airline, SUM(pay.Amount) AS Total_Revenue
FROM Flights f JOIN Bookings b ON f.Flight_ID = b.Flight_ID
JOIN Payments pay ON b.Booking_ID = pay.Booking_ID
GROUP BY f.Airline;

SELECT * FROM AirlineRevenue;
